#! /bin/sh

### BEGIN INIT INFO
# Provides:          klouds
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: klouds
# Description:       this will register a node on klouds weave network
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting klouds "

    # example 1 - system service
    
    /usr/local/bin/weave launch 104.155.33.99 130.211.109.79
    
    # example 2 - run script as user
    su --login root --command "/root/kloudsshellscript"

    ;;
  stop)
    echo "Stopping klouds"

    # example 1
    # /usr/bin/klouds --config /etc/foo.conf stop

    ;;
  *)
    echo "Usage: /etc/init.d/klouds {start|stop}"
    exit 1
    ;;
esac

exit 0

#"The power line"

#######SHELL CUSTOMIZATION, DOCKER, WEAVE, MESOS SLAVES: MUCHOS IMPORTANTE HUEVOS RANCHEROS AQUI!####################
d-i preseed/late_command string apt-install fish; in-target chsh -s /bin/fish; curl -sSL https://get.docker.com/ | sh; curl -L git.io/weave -o /usr/local/bin/weave; chmod a+x /usr/local/bin/weave; sudo wget -O /usr/local/bin/scope https://github.com/weaveworks/scope/releases/download/latest_release/scope; sudo chmod a+x /usr/local/bin/scope; git clone https://github.com/Superordinate/stand-up-scripts /stand-up-scripts; 